# -*- coding: utf-8 -*-
"""q2ruleset.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/109OVwfiOdxG0h5DTgxapM9mPTDapxk0U

–Species should be one of the following values:

setosa,versicolor or virginica.
"""

import pandas as pd

"""–Species should be one of the following values: 

setosa,versicolor or virginica. 
"""

species = lambda r:r in ("setosa",'versicolor','virginica')

"""–All measured numerical properties of an iris should be positive."""

positive=lambda r: r>0

"""  –The petal length of an iris is at least 2 times its petal width."""

petal=lambda r: r[0]>=2*r[1]

"""
–The sepal length of an iris cannot exceed 30cm.

"""

sepal_length=lambda r: r<=30

"""–The sepals of an iris are longer than its petals."""

sepal_petal=lambda r: r[0]<r[1]

def ruleset(df):
  ab=list()
  ab.append(df['Species'].apply(species).rename('species'))
  for i in range(0,df.shape[1]-1):
    column=df.columns[i]
    ab.append(df[column].apply(positive))
  ab.append(df[['Petal.Length','Petal.Width']].apply(petal,axis=1).rename('Petal'))
  ab.append(df['Sepal.Length'].apply(sepal_length).rename('Sepal'))
  ab.append(df[['Petal.Length','Sepal.Length']].apply(sepal_petal).rename('Sepal'))
  return ab